### ISSUE TITLE
Use safeTransfer in transferReward

### ISSUE THREAD

**Issue by jeremyHD** [CreamFi/liquidity-mining#4]
Goal is to prevent abnormal transfer behaviors on non standard ERC20 reward tokens

**Comment by jeremyHD** [comment]
Not sure if we need to consider reentry on transfer. Should also be careful on duplicate reward distribution

**Comment by bun919tw** [comment]
Reentry how?
`transferReward` is an internal function and could only be called by `claimRewards`.  `claimRewards` will update the related indexes so it should be to me. Also, we control the reward token lists. Normally we won't support weird tokens, right?

**Comment by jeremyHD** [comment]
We might allow weird tokens to incentive their own market some day. 

In this case, calling `IERC20(rewardToken).transfer(user, amount)` in `transferReward()` could reenter and call claimReward again before `IERC20(rewardToken).transfer(user, amount)` returns. Is this possible?

**Comment by bun919tw** [comment]
I could add reentry protection in `claimRewards`.

However, I still don't think we should let everyone use this LM module to distribute any arbitrary token. What if a malicious reward token asked for the allowance of other tokens in its `transfer` function? Reentry protection can't stop this attack. In my opinion, we should control the reward token list because the comptroller will distribute the rewards accordingly.

**Comment by jeremyHD** [comment]
Make sense. See if safeTransfer can make things better so we don’t need reentry protection

**Comment by bun919tw** [comment]
I think it's two different things.
1. `safeTransfer` is needed because we might support non-standard ERC20 tokens like USDT.
2. We can't control the transfer implementation so we need to control the reward token list. If we control the reward token list, yes, I think we don't need reentry protection here.

**Comment by jeremyHD** [comment]
Understood. I got mixed up on that. Sorry 😅
